# Ruby-Box2D : Yet another Box2D wrapper for Ruby
#
# * https://github.com/vaiorabbit/box2d-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module Box2D
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct


  # Function

  def self.setup_collision_inline_symbols(output_error = false)
    symbols = [
      :b2DynamicTree_GetUserData,
      :b2DynamicTree_GetAABB,
    ]
    apis = {
      :b2DynamicTree_GetUserData => :DynamicTree_GetUserData,
      :b2DynamicTree_GetAABB => :DynamicTree_GetAABB,
    }
    args = {
      :b2DynamicTree_GetUserData => [:pointer, :int],
      :b2DynamicTree_GetAABB => [:pointer, :int],
    }
    retvals = {
      :b2DynamicTree_GetUserData => :int,
      :b2DynamicTree_GetAABB => AABB.by_value,
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

