# Ruby-Box2D : Yet another Box2D wrapper for Ruby
#
# * https://github.com/vaiorabbit/box2d-bindings
#
# [NOTICE] Autogenerated. Do not edit.

require 'ffi'

module Box2D
  extend FFI::Library
  # Define/Macro


  # Enum


  # Typedef


  # Struct

  class WorldId < FFI::Struct
    layout(
      :index1, :ushort,
      :revision, :ushort,
    )
    def index1 = self[:index1]
    def index1=(v) self[:index1] = v end
    def revision = self[:revision]
    def revision=(v) self[:revision] = v end
    def self.create_as(_index1_, _revision_)
      instance = WorldId.new
      instance[:index1] = _index1_
      instance[:revision] = _revision_
      instance
    end
  end

  class BodyId < FFI::Struct
    layout(
      :index1, :int,
      :world0, :ushort,
      :revision, :ushort,
    )
    def index1 = self[:index1]
    def index1=(v) self[:index1] = v end
    def world0 = self[:world0]
    def world0=(v) self[:world0] = v end
    def revision = self[:revision]
    def revision=(v) self[:revision] = v end
    def self.create_as(_index1_, _world0_, _revision_)
      instance = BodyId.new
      instance[:index1] = _index1_
      instance[:world0] = _world0_
      instance[:revision] = _revision_
      instance
    end
  end

  class ShapeId < FFI::Struct
    layout(
      :index1, :int,
      :world0, :ushort,
      :revision, :ushort,
    )
    def index1 = self[:index1]
    def index1=(v) self[:index1] = v end
    def world0 = self[:world0]
    def world0=(v) self[:world0] = v end
    def revision = self[:revision]
    def revision=(v) self[:revision] = v end
    def self.create_as(_index1_, _world0_, _revision_)
      instance = ShapeId.new
      instance[:index1] = _index1_
      instance[:world0] = _world0_
      instance[:revision] = _revision_
      instance
    end
  end

  class JointId < FFI::Struct
    layout(
      :index1, :int,
      :world0, :ushort,
      :revision, :ushort,
    )
    def index1 = self[:index1]
    def index1=(v) self[:index1] = v end
    def world0 = self[:world0]
    def world0=(v) self[:world0] = v end
    def revision = self[:revision]
    def revision=(v) self[:revision] = v end
    def self.create_as(_index1_, _world0_, _revision_)
      instance = JointId.new
      instance[:index1] = _index1_
      instance[:world0] = _world0_
      instance[:revision] = _revision_
      instance
    end
  end

  class ChainId < FFI::Struct
    layout(
      :index1, :int,
      :world0, :ushort,
      :revision, :ushort,
    )
    def index1 = self[:index1]
    def index1=(v) self[:index1] = v end
    def world0 = self[:world0]
    def world0=(v) self[:world0] = v end
    def revision = self[:revision]
    def revision=(v) self[:revision] = v end
    def self.create_as(_index1_, _world0_, _revision_)
      instance = ChainId.new
      instance[:index1] = _index1_
      instance[:world0] = _world0_
      instance[:revision] = _revision_
      instance
    end
  end


  # Function

  def self.setup_id_symbols(output_error = false)
    symbols = [
    ]
    apis = {
    }
    args = {
    }
    retvals = {
    }
    symbols.each do |sym|
      begin
        attach_function apis[sym], sym, args[sym], retvals[sym]
      rescue FFI::NotFoundError => error
        $stderr.puts("[Warning] Failed to import #{sym} (#{error}).") if output_error
      end
    end
  end

end

